name: Update Match Data

on:
  schedule:
    - cron: '*/5 * * * *'  # Her 15 dakikada bir çalışır
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium schedule

    - name: Run data scraper
      run: python goalmatches.py

    - name: Commit files
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add goal_maclar.json goal_bitmis_maclar.json
        git commit -m 'Update match data'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
