name: Scheduled Data Fetch and Update

on:
  push:
    branches:
      - main  # Sadece main branch'e push yapıldığında tetikle
  schedule:
    - cron: "*/1 * * * *"  # Her dakika çalıştır

jobs:
  fetch_and_update:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install requests selenium schedule
          # Eğer requirements.txt dosyanız varsa aşağıdaki satırı kullanabilirsiniz
          # if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi

      - name: Run data fetching script
        run: python goalmatches.py  # goalmatches.py dosyanızın adını ve yolunu belirtin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Token'ınızı secrets'tan alın
