name: Scheduled Data Fetch and Update

on:
  push:
    branches:
      - main  # Sadece main branch'e push yapıldığında tetikle
  schedule:
    - cron: "*/10 * * * *"  # Her dakika çalıştır

jobs:
  fetch_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Python sürümünü istediğiniz bir sürümle değiştirin

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install requests selenium schedule

      - name: Run data fetching script
        run: python goalmatches.py  # goalmatches.py dosyanızın adını ve yolunu belirtin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Token'ınızı secrets'tan alın

      - name: Commit and push updated files
        if: always()  # Her durumda devam etmesini sağlar
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Dosya değişikliklerini ekleyin
          git add .
          
          # Değişiklikleri commit edin
          git commit -m "Auto-update data files"
          
          # Güncellemeleri GitHub'a push edin
          git push
