name: Update Scores

on:
  schedule:
    - cron: '*/1 * * * *'  # Her dakikada bir çalıştır
  push:
    branches:
      - main

jobs:
  update_scores:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests schedule

    - name: Install Chrome
      run: |
        choco install googlechrome

    - name: Get Chrome version
      id: chrome-version
      run: |
        powershell "(Get-Item 'C:\Program Files\Google\Chrome\Application\chrome.exe').VersionInfo.ProductVersion" | Out-File -FilePath chrome_version.txt -Encoding utf8
        echo "Chrome version: $(cat chrome_version.txt)"

    - name: Download ChromeDriver
      run: |
        $chrome_version = Get-Content chrome_version.txt
        $chrome_version_split = $chrome_version -split '\.'
        $major_version = $chrome_version_split[0]
        $chromedriver_version = Invoke-RestMethod -Uri "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$major_version"
        Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/$chromedriver_version/chromedriver_win32.zip" -OutFile "chromedriver_win32.zip"
        Expand-Archive chromedriver_win32.zip -DestinationPath "chromedriver"
        Move-Item -Path "chromedriver/chromedriver.exe" -Destination "C:\Program Files\Google\Chrome\Application\chromedriver.exe"

    - name: Add ChromeDriver to PATH
      run: |
        echo "::add-path::C:\Program Files\Google\Chrome\Application"

    - name: List files for debugging
      run: dir

    - name: Run Python script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python ./goalmatches.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Update scores'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
