name: Scheduled Data Fetch and Update

on:
  push:
    branches:
      - main  # Sadece main branch'e push yapıldığında tetikle
  schedule:
    - cron: "*/15 * * * *"  # Her 15 dakikada bir çalıştır

jobs:
  fetch_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Python sürümünü istediğiniz bir sürümle değiştirin

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install requests selenium schedule

      - name: Run data fetching script
        id: fetch-data
        run: python goalmatches.py  # goalmatches.py dosyanızın adını ve yolunu belirtin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Token'ınızı secrets'tan alın

      - name: Check if data has changed
        id: check-changes
        run: |
          git diff --quiet || echo "::set-output name=changed::true"
        working-directory: ${{ github.workspace }}

      - name: Commit and push updated files
        if: steps.check-changes.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add .
          git commit -m "Auto-update data files"
          git push
