name: Scheduled Data Fetch and Update

on:
  push:
    branches:
      - main  # Sadece main branch'te push yapıldığında tetikle
  schedule:
    - cron: "*/1 * * * *"  # Her dakika çalıştır

jobs:
  fetch_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Python sürümünüzü belirtin

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Gereksinimlerinizi belirtin, eğer varsa

      - name: Run data fetching script
        run: goalmatches.py  # Python script'inizin yolunu belirtin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Token'ınızı secrets'tan alın
